### ISSUE TITLE
Composer Process Timeout issue

### ISSUE THREAD

**Issue by simpleapps-io** [ramsey/devtools-lib#83]
When running composer dev:lint:fix on very large files I have been experiencing a timeout at 60 seconds. It appears that in the Process and ProcessFactory classes the $timeout variable for the Symfony process is getting reset to 60 from whatever composer has set in the config since it is not getting passed along. I did some testing and by placing the variable in the process::_construct and ProcessFactory::factory functions they override to what is in those files. Although a cannot see where to make sure these are in place to make the composer config value move through the command properly.

Thoughts?

**Comment by ramsey** [comment]
I think adding a line like this to the command would fix this issue:

https://github.com/ramsey/composer-repl/blob/01ee7a904363b339cfb96a278268d107b593b56c/src/Composer/ReplCommand.php#L66

Can you try running it with `--timeout=0` to see if that affects it?

```shell
composer dev:lint:fix --timeout=0
```

If it runs fine like this, then adding the line mentioned above to the command will fix it.

**Comment by simpleapps-io** [comment]
that command fails for me.

![composer-timeout](https://user-images.githubusercontent.com/66499666/141502097-6c9d41a5-624a-41d7-bcde-dd58414ca70c.PNG)
.

**Comment by ramsey** [comment]
My apologies. I thought `--timeout` was a global Composer option. It turns out that it's only an option for `run-script`. I'll do some testing and consider adding a `--timeout` option to all commands in devtools-lib. I think that might help no only in this case but in others.

Thanks!

**Comment by simpleapps-io** [comment]
FYI: I removed the vendor folders and updated composer and my performance issue went away. This no longer had any urgency for me.

**Comment by mallardduck** [comment]
I've started to run into this issue too - I was hoping that the `process-timeout` value in `composer.json` would help. However it doesn't actually seem to change anything at all for me. In my case I encounter the issue when the CI coverage runs. An example of this is here: https://github.com/KickflipCli/kickflip-src/runs/4688835529?check_suite_focus=true

**Comment by simpleapps-io** [comment]
I ended up creating a separate script that does the linting/testing for me. I only have one package that is impacted by this, and frankly, the code is huge and getting larger each week. Even with a proper timeout, I would end up needing to adjust the timeout probably once a month. Using my separate script there is no timeout at all.

**Comment by mallardduck** [comment]
Initially I explored overriding the CI coverage script today, while it worked I was quickly bit by the issue again. So while that is a valid route, I think there's a lot of value in adjust the timeout here instead.

If we don't try to fix it here then I have to replace yet another default command with a script. That just seems like a bad time. Especially since if we can adjust the timeout here then I can remove the script I added.

---

@ramsey - I want to send a PR to address the issues I'm encountering. I see two simple ways to accomplish a fix here:

1. Increase the timeout for all commands across the board,
2. Implement a timeout flag to allow users to set the value.

I'm inclined to consider option 1 since it seems to not be affecting too many folks. At least going by this issue here. TBH not sure how best to pull off 2, but my gut feel is that more users should be affected for that level of effort.

So maybe we can increase the timeout within `ProcessCommand::doExecute()`? Symfony docs show default being `60s` which seems rather low, maybe we just increase it to `300s`?

**Comment by mallardduck** [comment]
Here's an example where only one matrix variant passes, just because it happens to be 3s shy of 60s. Where as the rest of the actions failed:

https://github.com/KickflipCli/kickflip-src/runs/4697463584?check_suite_focus=true

**Comment by ramsey** [comment]
Is the issue with the Process timeout or the Composer timeout? They're two separate things.

**Comment by mallardduck** [comment]
That's the perplexing part - the error does link to the composer docs citing the [`process-timeout`](https://getcomposer.org/doc/06-config.md#process-timeout) option. However you'll note that this values default is 300s.

The exception that gets thrown is `Symfony\Component\Process\Exception\ProcessTimedOutException` and the time it fails on is `60s`. Both of which line up with the Symfony `Process` [default timeout value](https://symfony.com/doc/current/components/process.html#process-timeout).

Overall I think what's happening is that Symfony is triggering the exception and composer is also wrapping the exception and inserting the link.

```
The process "/home/runner/work/kickflip-src/kickflip-src/vendor/bin/phpunit '--colors=always'" exceeded the timeout of 60 seconds.
Check https://getcomposer.org/doc/06-config.md#process-timeout for details

                                                                                                                                      
  [Symfony\Component\Process\Exception\ProcessTimedOutException]                                                                      
  The process "/home/runner/work/kickflip-src/kickflip-src/vendor/bin/phpunit '--colors=always'" exceeded the timeout of 60 seconds.  
  ```
  
  That also kinda lines up as the exceptions message doesn't have anything related to the "Check .... for details" part of above.

**Comment by mallardduck** [comment]
Ohh, what if we make sure the Symfony Process runner's timeout mirrors the composer timeout value? Something like:

```
$process->setTimeout($this->getConfiguration()->getComposer()->getConfig()->get('process-timeout'));
```

**Comment by mallardduck** [comment]
BTW @simpleapps-io - with the PR #88 merged in you can now control the timeout value via composer's `process-timeout` config value. I know you said you made a script as a workaround, however this provides a new method to solve the issue.

In any case, between the new functionality via the PR and your method of a script workaround I believe this is resolved. Or at least this should be considered resolved IMHO.
