### ISSUE TITLE
Bug with composer 2.x and devtools binary

### ISSUE THREAD

**Issue by ncou** [ramsey/devtools-lib#85]
Hi,

Interesting package. I have found that the latest composer version broke the devtools binary (https://github.com/ramsey/devtools-lib/blob/main/bin/devtools#L62).
You can see in your latest githubaction result the error :

```php
Run ./bin/devtools test:unit
composer/package-versions-deprecated contains a Composer plugin which is currently not in your allow-plugins config. See https://getcomposer.org/allow-plugins
PHP Fatal error:  Uncaught Symfony\Component\Console\Exception\InvalidArgumentException: The helper "question" is not defined. in /home/runner/work/devtools-lib/devtools-lib/vendor/symfony/console/Helper/HelperSet.php:70 php
```

Composer try to ask a question to update the "allow-plugin" section in the composer.json file (@see https://getcomposer.org/allow-plugins).
If you add a new QuestionHelper() in the new HelperSet() parameters it will result in a infinite loop with the question [I don't know why]. There is 3 possibilities to sole this : 

1 - add a non interactive flag on the input object ($input->setInteractive(false);) i think it's the best solution.
2 - or when you create the composer instance you use the 3rd parameter to disable the plugins. (Factory::create($io, null, true);).
3 - Find why the question is asked in a infinite loop and avoid this problem :-) (but i didn"t find the "why" !!!)
[4 - Add the allow-plugin tag in the composer.json file to be ready for the futur composer version].

Hope this help.

**Comment by ramsey** [comment]
> You can see in your latest githubaction result the error

Can you provide a link to the error, please? I can't find it.

**Comment by ncou** [comment]
Here is the error in a previous build (8 days ago) using composer 2.2.1 :
https://github.com/ramsey/devtools-lib/runs/4627805229?check_suite_focus=true#step:6:7

But this question seems to not be asked in composer 2.2.3 because in the latest build logs (run today) i can't find this error.

**Comment by ramsey** [comment]
Oddly enough, the fatal error is not related to the `allow-plugin` property, since lack of that property should only emit a deprecation warning right now. The fatal error is due to some fluke with symfony/console that seems to have been resolved.

I did as `allow-plugin` in 963119b8b66a76b904be6e3e2cbf4b8c22e6cfba, so that should take care of the deprecation warning.

Thanks!
