### ISSUE TITLE
phpunit not working with windows in the workflow

### ISSUE THREAD

**Issue by ncou** [ramsey/devtools-lib#86]
Hi,

There is problem with the Windows environments. The phpunit command is not triggered because the binary is not correctly called.

`./bin/devtools test:unit` should be remplaced with `php bin/devtools test:unit` so this will work with both unix & windows systems.

But you will have some errors in the tests because the DIRECTORY_SEPARATOR constante is used so some tests will fails (ex : with windows the constructed path will be "/path/to/bin\foo" and it will compare in the phpunit a value of "/path/to/bin/foo").

I could try to do a PR if you wish.

**Comment by ramsey** [comment]
What is the error message you're getting?

**Comment by ncou** [comment]
There is no error message, i think it try to execute it as a shell instead as a php file.
You can see here that phpunit is not run (windows-latest) :
https://github.com/ramsey/devtools-lib/runs/4676940542?check_suite_focus=true#step:6:3

And here is the result when phpunit is run (ubuntu-latest) :
https://github.com/ramsey/devtools-lib/runs/4676940528?check_suite_focus=true#step:6:1

**Comment by ramsey** [comment]
Thanks for pointing this out. I've fixed this with the commits 3171424851a2cc80014ff77a3fb287ed5332a244, 98222430431231054904b4ebb166a43f634cdef2, and 60ef27be133cd4a8bed7cbe041601e3f83cebb31.

Happy New Year!

**Comment by ncou** [comment]
Happy new year :)
Beware of the captainhook config file, you will encounter the same problem on Windows.
https://github.com/ramsey/devtools-lib/blob/main/captainhook.json#L46
https://github.com/ramsey/devtools-lib/blob/main/captainhook.json#L55

**Comment by ramsey** [comment]
I don't know how to call the commands on Windows, and I don't have access to a Windows machine. How should these be written so that they work cross-platform?

**Comment by ncou** [comment]
I am on windows (yes some of us are using this OS :-) ) and i use "php bin/devtools xxxxx" in the captainhook file (and composer.json) and it's working fine. I think the first line in devtools `#!/usr/bin/env php` is used to implicitely call the php executable to interpret the script, but on windows you need to specificaly tell him to use "php" to interpret the file.
